ExpenseClient/Models/Oven.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Web;

namespace ExpenseClient.Models
{
    //DataContract for Serializing Data - required to serve in JSON format
    [DataContract]
    public class Oven
    {
        public Oven(double? x, double? y)
        {
            this.x = x;
            this.Y = y;
        }

        //Explicitly setting the name to be used while serializing to JSON.
        [DataMember(Name = "x")]
        public Nullable<double> x = null;

        //Explicitly setting the name to be used while serializing to JSON.
        [DataMember(Name = "y")]
        public Nullable<double> Y = null;

        

    }

    
}

ExpenseClient/ViewModels/OvenViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace ExpenseClient.ViewModels
{
    public class OvenViewModel
    {
        [Display(Name = "Cycles for Oven A")]
        public int? CycleNum { get; set; }

        [Display(Name = "Cycles for Oven A")]
        public List<CycleDropDown> cycleDropDownProperty { get; set; }
        public string CycleNumber { get; set; }

        [Display(Name = "Cycles for Oven B")]
        public List<OvenBCycleDropDown> ovenBCycleDropDownProperty { get; set; }

        [Display(Name = "Cycles for Oven B")]
        public int? CycleNumm { get; set; }

        public class CycleDropDown
        {
            public int? cycleNum { get; set; }
        }

        public class OvenBCycleDropDown
        {
            public int? cycleNumm { get; set; }
        }
        

       
    }
}

ExpenseClient/Controllers/ChartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using System.Data.SqlClient;
using System.Data;
using ExpenseClient.Models;
using ExpenseClient.ViewModels;
using static ExpenseClient.ViewModels.OvenViewModel;

namespace ExpenseClient.Controllers
{
    public class ChartController : Controller
    {
        private Press_2_DCEntities _db = new Press_2_DCEntities();

        public List<CycleDropDown> GetDetails() //populate dropdown and model bind
        {
            
            List<CycleDropDown> results = new List<CycleDropDown>();

            using (var _context = new Press_2_DCEntities())
            {
                var obj = _context.tblHeat_Treat_Log
                    .Select(x => x.Cycle_Num_A)
                    .Distinct()
                    .OrderByDescending(x => x);
                    
                if (obj != null && obj.Count() > 0)
                {
                    foreach (var data in obj)
                    {
                        CycleDropDown model = new CycleDropDown();
                        model.cycleNum = data;
                        results.Add(model);
                    }
                }
            }

            return results;
        }

        public List<OvenBCycleDropDown> GetDetailss() //populate dropdown and model bind
        {

            List<OvenBCycleDropDown> results = new List<OvenBCycleDropDown>();
            using (var _context = new Press_2_DCEntities())
            {
                var obj = _context.tblHeat_Treat_Log
                    .Select(x => x.Cycle_Num_B)
                    .Distinct()
                    .OrderByDescending(x => x);

                if (obj != null && obj.Count() > 0)
                {
                    foreach (var data in obj)
                    {
                        OvenBCycleDropDown model = new OvenBCycleDropDown();
                        model.cycleNumm = data;
                        results.Add(model);
                    }
                }
            }
            return results;
        }

        public ActionResult Index()
        {

            return View();
        }
        
        public ActionResult Ovens()
        {
            
            return View();
        }

        public ActionResult OvenCycles()
        {
            OvenViewModel model = new OvenViewModel();
            model.cycleDropDownProperty = GetDetails();
            model.ovenBCycleDropDownProperty = GetDetailss();
            return View(model);
        }

        // Parse Weekendingdate to JSON readable format
        public double weekend(DateTime now)
        {
            DateTime date = new DateTime(now.Year, now.Month, now.Day, now.Hour, now.Minute, now.Second);
            double time = ((DateTimeOffset)date).ToUnixTimeSeconds() * 1000;
            return time;
        }

        public ContentResult EXTPRESSURE()
        {
            List<DataPoint> dataPoints = new List<DataPoint>();
            dataPoints.Clear();

            foreach (var data in _db.qryEXT_Pressure_Info)
            {
                dataPoints.Add(new DataPoint(weekend(DateTime.Parse(data.Date_Time_Stamp.ToString())), data.EXT_Pressure));
            }

            return Content(JsonConvert.SerializeObject(dataPoints, _jsonSetting), "application/json");
        }

        JsonSerializerSettings _jsonSetting = new JsonSerializerSettings() { NullValueHandling = NullValueHandling.Ignore };

        public ContentResult OvenAJSON()
        {
            List<Oven> dataPoints = new List<Oven>();
            
            dataPoints.Clear();
           
            foreach (var data in _db.qryHT_Max_A_1_)
            {
                dataPoints.Add(new Oven(1, data.Zone1A));
                dataPoints.Add(new Oven(2, data.Zone2A));

            }

            return Content(JsonConvert.SerializeObject(dataPoints, _jsonSetting), "application/json");

        }

        public ContentResult OvenBJSON()
        {
            List<Oven> dataPoints = new List<Oven>();
            
            dataPoints.Clear();

            foreach (var data in _db.qryHT_Max_B_1_)
            {
                dataPoints.Add(new Oven(1, data.Zone1B));
                dataPoints.Add(new Oven(2, data.Zone2B));
            }

            return Content(JsonConvert.SerializeObject(dataPoints, _jsonSetting), "application/json");
        }

        public ContentResult PRESSEXIT()
        {
            var run = _db.qryEXT_Pressure_Info.Select(x => x.Run_Num).ToList();
            int runNumber = Convert.ToInt32(run[0]);

            List<DataPoint> dataPoints = new List<DataPoint>();
            dataPoints.Clear();            

            foreach (var data in _db.qryEXT_Pressure_Info.Where(m => m.Run_Num == runNumber))
            {
                dataPoints.Add(new DataPoint(weekend(DateTime.Parse(data.Date_Time_Stamp.ToString())), data.Press_Exit));
            }

            return Content(JsonConvert.SerializeObject(dataPoints, _jsonSetting), "application/json");
        }

        public ContentResult CycleZone1A(string input)
        {            
            List<DataPoint> dataPoints = new List<DataPoint>();
            dataPoints.Clear();
            int? cycle = Convert.ToInt32(input);

            foreach (var data in _db.tblHeat_Treat_Log.Where(m => m.Cycle_Num_A == cycle))
            {
                dataPoints.Add(new DataPoint(weekend(DateTime.Parse(data.Date_Time_Stamp.ToString())), data.Zone1A));
            }
                  
            return Content(JsonConvert.SerializeObject(dataPoints, _jsonSetting), "application/json");

        }

        public ContentResult CycleZone2A(string input)
        {
            List<DataPoint> dataPoints = new List<DataPoint>();
            dataPoints.Clear();

            int? cycle = Convert.ToInt32(input);

            foreach (var data1 in _db.tblHeat_Treat_Log.Where(m => m.Cycle_Num_A == cycle))
            {
                dataPoints.Add(new DataPoint(weekend(DateTime.Parse(data1.Date_Time_Stamp.ToString())), data1.Zone2A));
            }

            return Content(JsonConvert.SerializeObject(dataPoints, _jsonSetting), "application/json");
        }

        public ContentResult CycleZone1B(string input)
        {
            List<DataPoint> dataPoints = new List<DataPoint>();
            dataPoints.Clear();

            int? cycle = Convert.ToInt32(input);

            foreach (var data1 in _db.tblHeat_Treat_Log.Where(m => m.Cycle_Num_B == cycle))
            {
                dataPoints.Add(new DataPoint(weekend(DateTime.Parse(data1.Date_Time_Stamp.ToString())), data1.Zone1B));
            }

            return Content(JsonConvert.SerializeObject(dataPoints, _jsonSetting), "application/json");
        }

        public ContentResult CycleZone2B(string input)
        {
            List<DataPoint> dataPoints = new List<DataPoint>();
            dataPoints.Clear();

            int? cycle = Convert.ToInt32(input);

            foreach (var data1 in _db.tblHeat_Treat_Log.Where(m => m.Cycle_Num_B == cycle))
            {
                dataPoints.Add(new DataPoint(weekend(DateTime.Parse(data1.Date_Time_Stamp.ToString())), data1.Zone2B));
            }

            return Content(JsonConvert.SerializeObject(dataPoints, _jsonSetting), "application/json");
        }
    }
}

ExpenseClient/Views/Chart/Index.cshtml
@{
    ViewBag.Title = "Asynchronous Press Charting";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE HTML>
<html>
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
    
    
    <style>
        .chartContainer {
            width: 550px;
            margin-left: 10px;
            margin-right: 10px;
            margin-bottom: 30px;
        }

        canvas {
            -moz-user-select: none;
            -webkit-user-select: none;
            -ms-user-select: none;
        }

        .containerr {
            display: flex;
            flex-direction: row;
            flex-wrap: wrap;
        }

        #wrapper {
            display: flex;
            align-items: center;
            justify-content: center;
        }

    </style>
    <script>
        window.onload = function () {

            var pressureData = [];
            var exitData = [];
            var ovenAData = [];
            var ovenBData = [];

            updatePressure(); //Initialize
            updateExit();
            fillOvenA();
            fillOvenB();


            function updatePressure() {     //EXT PRESSURE UPDATE
                $.getJSON("/chart/EXTPRESSURE", pressureCallBack);


            };

            function updateExit() {    //PRESS EXIT UPDATE
                $.getJSON("/chart/PRESSEXIT", exitCallBack);

            };

            function fillOvenA() {      //OVEN A UPDATE
                $.getJSON("/chart/OvenAJSON", ovenACallBack);
            };

            function fillOvenB() {      //OVEN B UPDATE
                $.getJSON("/chart/OvenBJSON", ovenBCallBack);
            };

            function pressureCallBack(data) {   //EXT PRESSURE CALLBACK
                pressureData = data;
                addPressurePoints(chart, pressureData);
            }

            function exitCallBack(data) {       //PRESS EXIT CALLBACK
                exitData = data;
                addExitPoints(chart2, exitData);
            }

            function ovenACallBack(data) {  //OVEN A CALLBACK
                ovenAData = data;
                addOvenAData(chart3, ovenAData);
            }

            function ovenBCallBack(data) {  //OVEN B CALLBACK
                ovenBData = data;
                addOvenBData(chart4, ovenBData);
            }

            function addPressurePoints(chart, data) {     //EXT PRESSURE ADD - 30s Timeout
                chart.reset();
                chart.data.datasets[0].data = data;
                chart.update();
                setTimeout(updatePressure, 30000);
            };

            function addExitPoints(chart, data) {    //PRESS EXIT ADD - 30s Timeout
                chart.reset();
                chart.data.datasets[0].data = data;
                chart.update();
                setTimeout(updateExit, 30000);
            };

            function addOvenAData(chart, data) {    //OVEN A ADD - 30s Timeout

                chart.reset();
                chart.data.datasets[0].data = [{ x: data[0].y, y: data[0].x }];
                chart.data.datasets[1].data = [{ x: data[1].y, y: data[1].x }];
                chart.update();
                setTimeout(fillOvenA, 30000);
            };
            function addOvenBData(chart, data) {    //OVEN B ADD - 30s Timeout

                chart.reset();
                chart.data.datasets[0].data = [{ x: data[0].y }];
                chart.data.datasets[1].data = [{ x: data[1].y }];
                chart.update();
                setTimeout(fillOvenB, 30000);
            };

            var ctxx = document.getElementById('myCycleChart').getContext('2d');
            var ctx = document.getElementById('myChart').getContext('2d');
            var ovenACtx = document.getElementById('ovenAChart').getContext('2d');
            var ovenBCtx = document.getElementById('ovenBChart').getContext('2d');

            var chart4 = new Chart(ovenBCtx, {      //Oven B
                type: 'horizontalBar',
                data: {
                    datasets: [{
                        label: 'Zone1B',
                        backgroundColor: 'rgba(164, 222, 229, 1)',
                        data: ovenBData
                    }, {
                        label: 'Zone2B',
                        backgroundColor: 'rgba(130, 60, 200, 1)',
                        data: ovenBData
                    }
                    ]
                },
                labels: [],
                options: {
                    scales: {
                        xAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                }
            });

            var chart3 = new Chart(ovenACtx, {      //Oven A
                type: 'horizontalBar',
                data: {
                    datasets: [{
                        label: 'Zone1A',
                        backgroundColor: 'rgba(164, 222, 229, 1)',
                        data: ovenAData,
                    }, {
                        label: 'Zone2A',
                        backgroundColor: 'rgba(130, 60, 200, 1)',
                        data: ovenAData
                    }
                    ]
                },
                labels: [],
                options: {
                    scales: {
                        xAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                }
            });

            var chart2 = new Chart(ctxx, {      //Press Exit
                type: 'line',
                data: {
                    datasets: [{
                        label: 'Press Exit',
                        backgroundColor: 'rgba(183, 230, 235, 1)',
                        borderColor: 'rgba(130, 60, 200, 1)', //'rgba(164, 222, 229, 1)',
                        data: exitData
                    }]
                },
                labels: [],
                options: {
                    scales: {
                        xAxes: [{
                            type: 'time',
                            time: { unit: 'minute' }

                        }]
                    },
                    elements: {
                        point: {
                            pointStyle: 'rectRounded'
                        }
                    }
                }
            });
            var chart = new Chart(ctx, {           //EXT PRESSURE
                type: 'line',
                // The data for our dataset
                data: {
                    datasets: [{
                        label: 'EXT Pressure',
                        backgroundColor: 'rgba(183, 230, 235, 1)',
                        borderColor: 'rgba(130, 60, 200, 1)', //rgba(130, 60, 200, 1)
                        pointBackgroundColor: 'rgba(164, 222, 229, 1)',
                        data: pressureData
                    }]
                },
                labels: [],
                // Configuration options go here
                options: {
                    responsive: true,
                    scales: {
                        xAxes: [{
                            type: 'time',
                            time: { unit: 'minute' }

                        }]
                    },
                    elements: {
                        point: {
                            pointStyle: 'rectRounded'
                        }
                    }
                }
            });

        };

        function dropDown() {
            $('#hidden').show();

        }

        

    </script>



</head>
<body>
    
    @*<div class="page-header">
        <div class="content">
            <img src="~/Site Content/geiBrandBoot.png" style="text-align: center;" alt="GEI" />
            <h2>Real-Time Charting</h2>
            
        </div>
    </div>*@
    <div class="containerr" style="margin-top: 10px;">
        
        <div class="chartContainer" style="border-style: outset; border-color: cornflowerblue;">
            <h3 style="text-align: center;"><strong>EXT PRESSURE</strong></h3>
            <canvas id="myChart"></canvas>

        </div>
            
        <div class="chartContainer" style="border-style: outset; border-color: cornflowerblue;">
            <h3 style="text-align: center;"><strong>Press Exit</strong></h3>
            <canvas id="myCycleChart"></canvas>
        </div>
            
        <div class="chartContainer" style="border-style: outset; border-color: cornflowerblue;">
            <h3 style="text-align: center;"><strong>OVEN A</strong></h3>
            <canvas id="ovenAChart"></canvas>
        </div>
        <div class="chartContainer" style="border-style: outset; border-color: cornflowerblue;">
            <h3 style="text-align: center;"><strong>OVEN B</strong></h3>
            <canvas id="ovenBChart"></canvas>
        </div>
                          
    </div>
    <div class="container">
        
        <div id="wrapper">
            
            <div class="btn-group" role="group" aria-label="Basic example">
                <button type="button" class="btn btn-secondary" style="margin-right: 10px;"><span class="glyphicon glyphicon-menu-left"></span></button>
                <button type="button" onclick="location.href = '/Chart/Index';" class="btn btn-info"><span class="glyphicon glyphicon-refresh"></span></button>
                <button type="button" class="btn btn-secondary" style="margin-left: 10px;"><span class="glyphicon glyphicon-menu-right"></span></button>
            </div>
        </div>
        
        <button class="btn btn-primary" type="button" onclick="dropDown()">
            Announcements <span class="badge">4</span>
        </button>
        
        <div class="hidden" id="hidden">
            <div class="well">
                <h6>Hello this is my first announcement</h6>
            </div>
        </div>
        
                
    </div>
    
</body>
</html>

ExpenseClient/Views/Chart/Ovens.cshtml
@model ExpenseClient.ViewModels.OvenViewModel
@{
    ViewBag.Title = "Ovens";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE HTML>
<html>
<head>

    <script>
         window.onload = function () {

            // Initial Values            
             dataPoints = []; //Oven A
             dataSeries = []; // Oven B
             dataSeriess = []; // Cycle run - Zone1A
             dataSeriesss = []; // Cycle run - Zone2A

             var dataLength = 75; // number of dataPoints visible at any point

             var chart = new CanvasJS.Chart("chartContainer", { //Oven A
                 animationEnabled: true,
                 theme: "light2",
                 title: {
                     text: "Oven A"
                 },       
                 legend: {
                     horizontalAlign: "center",
                     verticalAlign: "top",
                     fontSize: 10
                 },                 
                 data: [{
                     type: "doughnut", 
                     cursor: "crosshair",
                     showInLegend: true,
                     indexLabelFontColor: "#00008B",
                     indexLabelFontSize: 16,
                     dataPoints: dataPoints
                    
                 }]
                
             });

             updateData();

             var chart2 = new CanvasJS.Chart("chartContainer2", { //Oven B
                 animationEnabled: true,
                 theme: "light2",
                 title: {
                     text: "Oven B"
                 },   
                 legend: {
                     horizontalAlign: "center",
                     verticalAlign: "top",
                     fontSize: 10
                 },
                 data: [{
                     type: "doughnut",   
                     cursor: "crosshair",
                     showInLegend: true,                     
                     indexLabelFontColor: "#00008B",
                     indexLabelFontSize: 16,
                     dataPoints: dataSeries
                    
                 }]
                
             });

             updateData2();

             var chart3 = new CanvasJS.Chart("chartContainer3", { //Cycle run
                 animationEnabled: true,
                 theme: "light2",
                 title: {
                     text: "Cycle x run"
                 },
                 data: [{
                     type: "splineArea",
                     xValueType: "dateTime",
                     cursor: "crosshair",
                     //color: "#00008B",
                     name: "Zone1A",
                     showInLegend: true,
                     dataPoints: dataSeriess
                         

                 },
                 {
                     type: "line",
                     xValueType: "dateTime",
                     cursor: "crosshair",
                     color: "#03fc94",
                     name: "Zone2A",
                     showInLegend: true,
                     dataPoints: dataSeriesss
                 },
                 ]
             });

             updateData3();

             function addData(data) { //Oven A

                $.each(data, function (key, value) {
                    
                    chart.data = [];
                    chart.data = dataPoints;
                    chart.options.data[0].dataPoints[0] = { name: "Zone1A", label: data[0].y, y: data[0].y };
                    chart.options.data[0].dataPoints[1] = { name: "Zone2A", label: data[1].y, y: data[1].y };
                    
                });
             
                chart.render();
                setTimeout(updateData, 60000);

             }

             function addData2(data) { //Oven B

                $.each(data, function (key, value) {
                    chart2.data = [];
                    chart2.data = dataPoints;                    
                    chart2.options.data[0].dataPoints[0] = { name: "Zone1B", label: data[0].y, y: data[0].y };
                    chart2.options.data[0].dataPoints[1] = { name: "Zone2B", label: data[1].y, y: data[1].y };
                    
                });
             
                chart2.render();
                setTimeout(updateData2, 60000);

             }

             function addData3(data) { //Cycle run

                $.each(data, function (key, value) {
                    chart3.data = [];
                    chart3.data = dataPoints;
                    dataSeriess.push({ x: value.x, y: parseFloat(value.y) });
                    dataSeriesss.push({ x: value.x, y: parseFloat(value.y) });
                });             
                chart3.render();
                
             }
            
             function updateData() {            //Oven A                
                $.getJSON("/chart/OvenJSON", addData);                
             }    

             function updateData2() {           //Oven B     
                $.getJSON("/chart/Oven2JSON", addData2);                
             }    

             function updateData3() {           //Cycle run    
                $.getJSON("/chart/CycleJSON", addData3);                
             } 
                        
         }
        
    </script>
</head>
<body>

    <div class="page-header">
        <div class="content">
            @*@using (Html.BeginForm("Ovens", "Chart"))
             {
                @Html.LabelFor(m => m.cycleDropDownProperty)
                @Html.DropDownListFor(m => m.CycleNum, new SelectList(Model.cycleDropDownProperty), "Select Cycle", new {  @class = "form-control" })
                    
             }*@


        </div>
    </div>
    <div class="container">
        <div class="content" style="justify-content: center;">

            <div id="chartContainer" style="height: 250px; width: 250px;">

            </div>
            <div id="chartContainer2" style="height: 250px; width: 250px; padding-left: 25px;">

            </div>
        </div>
        <div class="container" style="padding-top: 50px;">
            <div id="chartContainer3" style="height: 350px; width: 100%;">

            </div>
        </div>
        <script src="~/Scripts/jquery-3.4.1.min.js"></script>
        <script src="~/Scripts/canvasjs.min.js"></script>
    </div>
</body>
</html>