ExpenseClient/ViewModels/SalesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ExpenseClient.ViewModels
{
    public class SalesViewModel
    {
        [Display(Name = "Start Date")]
        public DateTime PromiseDateBegin { get; set; }

        [Display(Name = "End Date")]
        public DateTime PromiseDateEnd { get; set; }

        [Display(Name = "Customer Number(if required)")]
        public int CustomerNumber { get; set; }

        [Display(Name = "Sales Reports")]
        public List<SalesDropDown> salesDropDownProperty { get; set; }

        public string report { get; set; }               

        public class SalesDropDown
        {
            public string selected { get; set; }
        }
    }
}

ExpenseClient/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ExpenseClient.Models;
using ExpenseClient.ViewModels;
using Microsoft.Reporting.WebForms;
using Oracle.ManagedDataAccess.Client;
using static ExpenseClient.ViewModels.SalesViewModel;

namespace ExpenseClient.Controllers
{
    public class SalesController : Controller
    {
        public ActionResult Index()
        {
            SalesViewModel model = new SalesViewModel();
            model.salesDropDownProperty = GetDetails();
            model.PromiseDateBegin = DateTime.Now.AddDays(-1).Date;
            model.PromiseDateEnd = DateTime.Now.AddDays(1).Date;
            return View(model);
        }

        public List<SalesDropDown> GetDetails()
        {
            List<SalesDropDown> results = new List<SalesDropDown>();
            List<string> obj = new List<string>();
            //obj.Add("BOOKED BY CUST ACCTNUM");
            //obj.Add("BOOKED BY CUSTOMER");
            obj.Add("SALES BY CUSTOMER");
            obj.Add("SALES BY CUSTOMER(PRICE PER LB)");
            obj.Add("SALES REPORT BY SALES AMOUNT");
            obj.Add("SALES REPORT BY MONTH FOR SINGLE ACCOUNT");
            obj.Add("SALES REPORT BY DIE FOR SINGLE ACCOUNT");
            obj.Add("SALES REPORT BY ITEM FOR SINGLE ACCOUNT");

            foreach (var data in obj)
            {
                SalesDropDown model = new SalesDropDown();
                model.selected = data;
                results.Add(model);
            }
            
            return results;
        }              

        public ActionResult Router(SalesViewModel model)
        {
            //if (model.report == "BOOKED BY CUST ACCTNUM")
            //{
            //    return RedirectToAction("BookingsByAcctNum", model);
            //}
            //if (model.report == "BOOKED BY CUSTOMER")
            //{
            //    return RedirectToAction("BookingsByCustomer", model);
            //}
            if (model.report == "SALES BY CUSTOMER")
            {
                return RedirectToAction("SalesByCustomer", model);
            }
            if (model.report == "SALES BY CUSTOMER(PRICE PER LB)")
            {
                return RedirectToAction("SalesByCustomerPricePerLb", model);
            }
            if (model.report == "SALES REPORT BY SALES AMOUNT")
            {
                return RedirectToAction("SalesReportBySalesAmount", model);
            }
            if (model.report == "SALES REPORT BY MONTH FOR SINGLE ACCOUNT")
            {
                return RedirectToAction("SalesByAcctByMonth", model);
            }
            if (model.report == "SALES REPORT BY DIE FOR SINGLE ACCOUNT")
            {
                return RedirectToAction("SalesByDieByAcctNum", model);
            }
            if (model.report == "SALES REPORT BY ITEM FOR SINGLE ACCOUNT")
            {
                return RedirectToAction("SalesByItemByAcctNum", model);
            }
            else
            {
               return RedirectToAction("Index");
            }
        }

        //public ActionResult Index(SalesViewModel model) //overload
        //{

        //    return View();
        //}

        public ActionResult SalesReportBySalesAmount(SalesViewModel model)
        {
            ReportViewer rptViewer = new ReportViewer();
            G2ProdDataSet ds = new G2ProdDataSet();
            DateTime beginn = model.PromiseDateBegin.Date;
            DateTime endd = model.PromiseDateEnd.Date;
            string begin = beginn.Date.ToShortDateString();
            string end = endd.Date.ToShortDateString();
            int cxNum = model.CustomerNumber;

            string connectionString = "Data Source=(DESCRIPTION="
                    + "(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=gei-glovia)(PORT=1521)))"
                    + "(CONNECT_DATA=(SERVER=prod)(SERVICE_NAME=G2prod.gei.local)));"
                    + "User Id=glovia_prod;Password=manager;";

            OracleConnection connection = new OracleConnection(connectionString);

            OracleCommand cmd = new OracleCommand(
            "Select " +
                    "qrySHIPPED_QTY_INV_AMT.OTST_NAME, " +
                    "qrySHIPPED_QTY_INV_AMT.CUSTOMER, " +
                    "ROUND(Sum(qrySHIPPED_QTY_INV_AMT.SumSHIPPEDQTY), 2) As Sum_SHIPPEDQTY, " +
                    "ROUND(Sum(qrySHIPPED_QTY_INV_AMT.SumITEMWEIGHT), 2) As Sum_ITEMWEIGHT, " +
                    "ROUND(Sum(qrySHIPPED_QTY_INV_AMT.SumSALESAMT), 2) As Sum_SALESAMT " +
                "From " +
                    "(Select " +
                         "qrySO_SHIP_GRP.SALES_CCN, " +
                         "qrySO_SHIP_GRP.OTST_NAME, " +
                         "qrySO_SHIP_GRP.AR_DOC, " +
                         "qrySO_SHIP_GRP.SumSHIPPEDQTY, " +
                         "qrySO_SHIP_GRP.SumITEMWEIGHT, " +
                         "qrySO_SHIP_GRP.SumSALESAMT, " +
                         "qryAR_DOC.AMT, " +
                         "qrySO_SHIP_GRP.CUSTOMER, " +
                         "qrySO_SHIP_GRP.USER_ALPHA1, " +
                         "qrySO_SHIP_GRP.Prim_Acct " +
                     "From " +
                          "(Select " +
                               "qrySO_SHIP.SALES_CCN, " +
                               "qrySO_SHIP.OTST_NAME, " +
                               "qrySO_SHIP.AR_DOC, " +
                               "Sum(qrySO_SHIP.SHIPPED_QTY) As SumSHIPPEDQTY, " +
                               "Sum(qrySO_SHIP.ITEM_WEIGHT) As SumITEMWEIGHT, " +
                               "qrySO_SHIP.CUSTOMER, " +
                               "qrySO_SHIP.USER_ALPHA1, " +
                               "qrySO_SHIP.Prim_Acct, " +
                               "Sum(qrySO_SHIP.Sales_Amt) As SumSALESAMT " +
                           "From " +
                                "(Select " +
                                     "SALES_CCN, " +
                                     "SO, " +
                                     "SO_LINE, " +
                                     "AGC, " +
                                     "AGC_CODE, " +
                                     "ITEM, " +
                                     "REVISION, " +
                                     "SELL_UM, " +
                                     "SO_DELIVERY, " +
                                     "SO_SHIPMENT, " +
                                     "INVOICE_DATE, " +
                                     "SHIPPED_QTY, " +
                                     "NET_WEIGHT, " +
                                     "WT, " +
                                     "WT_FT, " +
                                     "TH_WGT, " +
                                     "MAS_LOC, " +
                                     "BOL, " +
                                     "STH_WGT, " +
                                     "TH_WT_PCT, " +
                                     "PCS_NET_WT, " +
                                     "ITEM_NET_WT, " +
                                     "(Case " +
                                         "When SubStr(AGC_CODE, 2) = 'OL' " +
                                         "Then 0 " +
                                         "When SELL_UM = 'MT' " +
                                         "Then ITEM_NET_WT * UM_SCALAR * SHIPPED_QTY " +
                                         "When SELL_UM = 'LB' " +
                                         "Then SHIPPED_QTY " +
                                         "When SELL_UM = 'FT' " +
                                         "Then WT_FT * SHIPPED_QTY " +
                                         "When SELL_UM = 'IN' " +
                                         "Then (WT_FT / 12) * SHIPPED_QTY " +
                                         "Else ITEM_NET_WT * SHIPPED_QTY " +
                                     "End) As ITEM_WEIGHT, " +
                                     "UM_SCALAR, " +
                                     "EXT_AMT As Sales_Amt, " +
                                     "AR_DOC, " +
                                     "CUSTOMER, " +
                                     "OTST_NAME, " +
                                     "USER_ALPHA1, " +
                                     "CUS_LOC, " +
                                     "(Case " +
                                         "When USER_ALPHA1 = ' ' " +
                                         "Then CUSTOMER " +
                                         "Else USER_ALPHA1 " +
                                     "End) As Prim_Acct " +
                                 "From " +
                                      "(Select " +
                                           "SALES_CCN, " +
                                           "SO, " +
                                           "SO_LINE, " +
                                           "AGC, " +
                                           "AGC_CODE, " +
                                           "ITEM, " +
                                           "REVISION, " +
                                           "Die, " +
                                           "SELL_UM, " +
                                           "SO_DELIVERY, " +
                                           "SO_SHIPMENT, " +
                                           "INVOICE_DATE, " +
                                           "SHIPPED_QTY, " +
                                           "NET_WEIGHT, " +
                                           "WT, " +
                                           "WT_FT, " +
                                           "TH_WGT, " +
                                           "BOL, " +
                                           "STH_WGT, " +
                                           "TH_WT_PCT, " +
                                           "PCS_NET_WT, " +

ExpenseClient/Views/Sales/BookingsByAcctNum.cshtml
@model ExpenseClient.ViewModels.SalesViewModel
@{
    ViewBag.Title = "BookingsByAcctNum";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using ReportViewerForMvc;

<div class="page-header">
    <div class="content">

    </div>
</div>

<div class="container">

    <div id="reportView" class="table-responsive">
        @Html.ReportViewer(ViewBag.ReportViewer as Microsoft.Reporting.WebForms.ReportViewer, new { scrolling = "no", width = "50%" })
    </div>
</div>

ExpenseClient/Views/Sales/BookingsByCustomer.cshtml
@model ExpenseClient.ViewModels.SalesViewModel
@{
    ViewBag.Title = "BookingsByCustomer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using ReportViewerForMvc;

<div class="page-header">
    <div class="content">

    </div>
</div>

<div class="container">

    <div id="reportView" class="table-responsive">
        @Html.ReportViewer(ViewBag.ReportViewer as Microsoft.Reporting.WebForms.ReportViewer, new { scrolling = "no", width = "50%" })
    </div>
</div>

ExpenseClient/Views/Sales/Index.cshtml
@model  ExpenseClient.ViewModels.SalesViewModel

@{
    ViewBag.Title = "Sales Reports";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using ReportViewerForMvc;

<div class="page-header">
    <div class="content">
        <h4>To get started please select a report & promise date</h4>
    </div>
</div>


@using (Html.BeginForm("Router", "Sales"))
{
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                @Html.LabelFor(m => m.salesDropDownProperty)
                @Html.DropDownListFor(m => m.report, new SelectList(Model.salesDropDownProperty, "selected", "selected"), "Select Item", new { @class="form-control" })
            </div>
            <div class="col-sm-2">
                @Html.LabelFor(m => m.PromiseDateBegin)
                @Html.TextBoxFor(m => m.PromiseDateBegin, new { @class = "form-control" })
            </div>
            <div class="col-sm-2">
                @Html.LabelFor(m => m.PromiseDateEnd)
                @Html.TextBoxFor(m => m.PromiseDateEnd, new { @class = "form-control" })
            </div>
            <div class="col-sm-3">
                @Html.LabelFor(m => m.CustomerNumber)
                @Html.TextBoxFor(m => m.CustomerNumber, new { @class = "form-control" })
            </div>
            <div class="col-sm-2" style="padding-top: 24px;">
                <button type="submit" class="btn btn-primary">Submit &raquo;</button> 
            </div>
        </div>
    </div>
}


<script>
    
</script>

ExpenseClient/Views/Sales/SalesByAcctByMonth.cshtml
@model ExpenseClient.ViewModels.SalesViewModel

@{
    ViewBag.Title = "SalesByAcctByMonth";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using ReportViewerForMvc;

<div class="page-header">
    <div class="content">

    </div>
</div>

<div class="container">

    <div id="reportView" class="table-responsive">
        @Html.ReportViewer(ViewBag.ReportViewer as Microsoft.Reporting.WebForms.ReportViewer, new { scrolling = "no", width = "50%" })
    </div>
</div>

ExpenseClient/Views/Sales/SalesByCustomer.cshtml
@model ExpenseClient.ViewModels.SalesViewModel
@{
    ViewBag.Title = "SalesByCustomer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using ReportViewerForMvc;

<div class="page-header">
    <div class="content">

    </div>
</div>

<div class="container">

    <div id="reportView" class="table-responsive">
        @Html.ReportViewer(ViewBag.ReportViewer as Microsoft.Reporting.WebForms.ReportViewer, new { scrolling = "no", width = "50%" })
    </div>
</div>

ExpenseClient/Views/Sales/SalesByCustomerPricePerLb.cshtml
@model ExpenseClient.ViewModels.SalesViewModel
@{
    ViewBag.Title = "SalesByCustomerPricePerLb";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using ReportViewerForMvc;

<div class="page-header">
    <div class="content">

    </div>
</div>

<div class="container">

    <div id="reportView" class="table-responsive">
        @Html.ReportViewer(ViewBag.ReportViewer as Microsoft.Reporting.WebForms.ReportViewer, new { scrolling = "no", width = "50%" })
    </div>
</div>

ExpenseClient/Views/Sales/SalesByDieByAcctNum.cshtml
@model ExpenseClient.ViewModels.SalesViewModel
@{
    ViewBag.Title = "SalesByDieByAcctNum";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using ReportViewerForMvc;

<div class="page-header">
    <div class="content">

    </div>
</div>

<div class="container">

    <div id="reportView" class="table-responsive">
        @Html.ReportViewer(ViewBag.ReportViewer as Microsoft.Reporting.WebForms.ReportViewer, new { scrolling = "no", width = "50%" })
    </div>
</div>

ExpenseClient/Views/Sales/SalesByItemByAcctNum.cshtml
@model ExpenseClient.ViewModels.SalesViewModel
@{
    ViewBag.Title = "SalesByItemByAcctNum";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using ReportViewerForMvc;

<div class="page-header">
    <div class="content">

    </div>
</div>

<div class="container">

    <div id="reportView" class="table-responsive">
        @Html.ReportViewer(ViewBag.ReportViewer as Microsoft.Reporting.WebForms.ReportViewer, new { scrolling = "no", width = "50%" })
    </div>
</div>

ExpenseClient/Views/Sales/SalesReportBySalesAmount.cshtml
@model ExpenseClient.ViewModels.SalesViewModel
@{
    ViewBag.Title = "SalesReportBySalesAmount";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using ReportViewerForMvc;

<div class="page-header">
    <div class="content">

    </div>
</div>

<div class="container">

    <div id="reportView" class="table-responsive">
        @Html.ReportViewer(ViewBag.ReportViewer as Microsoft.Reporting.WebForms.ReportViewer, new { scrolling = "no", width = "50%" })
    </div>
</div>