ExpenseClient/Controllers/ISWorkOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core.Mapping;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Infrastructure.MappingViews;
using System.Threading.Tasks;
using ExpenseClient.ViewModels;
using ExpenseClient.Models;
using System.Net.Mail;
using System.Threading;
using System.Security.Principal;
using System.Security.Authentication;
using System.Security.Permissions;
using System.IO;
using System.DirectoryServices.AccountManagement;
using System.DirectoryServices;
using System.Security.Claims;

namespace ExpenseClient.Controllers
{
    public class ISWorkOrderController : Controller
    {
        public List<CategoryDropDown> GetDetails() //populate dropdown and model bind
        {
            GEI_IS_WOEntities db = new GEI_IS_WOEntities();
            List<CategoryDropDown> results = new List<CategoryDropDown>();

            var obj = db.tblCategories.Select(m => m).ToList();
            if (obj != null && obj.Count() > 0)
            {
                foreach (var data in obj)
                {
                    CategoryDropDown model = new CategoryDropDown();
                    model.Category = data.Category;
                    model.Owner = data.Owner;                    
                    results.Add(model);
                }
            }

            return results;
        }
                
        public List<UrgencyDropDown> GetDetail()
        {
            GEI_IS_WOEntities db = new GEI_IS_WOEntities();
            List<UrgencyDropDown> results = new List<UrgencyDropDown>();
            var obj = db.tblImportances.Select(m => m).ToList();
            if (obj != null && obj.Count > 0)
            {
                foreach (var data in obj)
                {
                    UrgencyDropDown model = new UrgencyDropDown();
                    model.Urgency = data.Importance;
                    results.Add(model);
                }
            }

            return results;
        }

        // GET: WorkOrder
        public ActionResult Index()
        {
            string user = User.Identity.Name.Substring(9);
            WorkOrderViewModel model = new WorkOrderViewModel();
            model.MachineName = System.Environment.MachineName;    
            model.CategoryDropDown = GetDetails();
            model.UrgencyDropDown = GetDetail();
            model.Status = "Open";
            model.Date = DateTime.Now;
            model.Username = user;            
            
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(WorkOrderViewModel model)
        {
            string user = User.Identity.Name.Substring(9);
            //Any validation rules

            //Model and property binding
            GEI_IS_WOEntities db = new GEI_IS_WOEntities();
            tblMain dbo = new tblMain();
            model.DueDate = DateTime.Now.AddDays(1);
            model.Username = user;
            CreateCopyMessage("smtp.office365.com", model);            

            dbo.Category = model.category;
            dbo.Date = model.Date;
            dbo.Description = model.Description;
            dbo.Importance = model.Importance;
            dbo.Username = user;
            dbo.Comp_Name = model.MachineName;
            dbo.Status = model.Status;
            dbo.Status_Date = DateTime.Now;
            dbo.Due_Date = DateTime.Now.AddDays(1);

            db.tblMains.Add(dbo);
            db.SaveChanges();
            

            return RedirectToAction("Index"); //return to non-overloaded index
            
        }

        [Authorize(Roles = "WkstAdmin")]
        public ActionResult Admin()
        {
            
            return View();          
            
            
            
            
        }

        [HttpGet]
        public JsonResult LoadData()
        {
            using (GEI_IS_WOEntities dc = new GEI_IS_WOEntities())
            {
                string user = User.Identity.Name.Substring(9);
                WorkOrderViewModel model = new WorkOrderViewModel();
                model.UrgencyDropDown = GetDetail();
                model.CategoryDropDown = GetDetails();
                List<WorkOrderViewModel> List = dc.tblMains
                    .Where(m => m.Status == "Open")
                    .ToList()
                    .Select(m => new WorkOrderViewModel
                    {
                        category = m.Category,
                        Date = m.Date.Value.Date,
                        Username = m.Username,
                        Comp_Name = m.Comp_Name,
                        Importance = m.Importance,
                        Description = m.Description,
                        Status = m.Status,
                        StatusDate = m.Status_Date,
                        DueDate = m.Due_Date,
                        WorkOrderNumber = m.WorkOrderNum
                        
                    }).ToList();

                return Json(List, JsonRequestBehavior.AllowGet);

            }
        }
        
        public ActionResult EditOrder(int wo)
        {
            GEI_IS_WOEntities db = new GEI_IS_WOEntities();
            List<tblMain> list = db.tblMains.ToList();
            ViewBag.DepartmentList = list;

            WorkOrderViewModel model = new WorkOrderViewModel();
            model.CategoryDropDown = GetDetails();
            model.UrgencyDropDown = GetDetail();
            

            tblMain emp = db.tblMains.SingleOrDefault(x => x.WorkOrderNum == wo);
            model.Date = emp.Date;
            model.category = emp.Category;
            model.Username = emp.Username;
            model.MachineName = emp.Comp_Name;
            model.Importance = emp.Importance;
            model.Description = emp.Description;
            model.ISComments = emp.IS_Comments;
            model.Status = emp.Status;
            model.StatusDate = emp.Status_Date;
            model.DueDate = emp.Due_Date;
            model.WorkOrderNumber = emp.WorkOrderNum;

            
            return PartialView("WoPartial", model);
        }

        [HttpPost]
        public ActionResult Edit(WorkOrderViewModel model)
        {
            GEI_IS_WOEntities db = new GEI_IS_WOEntities();
            
                //Update
                var asset = db.tblMains.SingleOrDefault(x => x.WorkOrderNum == model.WorkOrderNumber);
                asset.Date = model.Date;
                asset.Username = model.Username;
                asset.Comp_Name = model.MachineName;
                asset.Category = model.category;
                asset.Importance = model.Importance;
                asset.Description = model.Description;
                asset.IS_Comments = model.ISComments;
                asset.Status = model.Status;
                asset.Status_Date = DateTime.Now.Date;
                asset.WorkOrderNum = model.WorkOrderNumber;
                asset.Due_Date = model.DueDate;
                
                db.SaveChanges();
                CreateResponse("smtp.office365.com", model);

            return RedirectToAction("Index");
            
            
        }

        public static void CreateCopyMessage(string server, WorkOrderViewModel model)
        {
            MailAddress from = new MailAddress("do_not_reply@genext.com", "Alan Bradley");
            MailAddress to = new MailAddress("IS_Dept@genext.com");
            MailMessage message = new MailMessage(from, to);
            // message.Subject = "Using the SmtpClient class.";
            message.IsBodyHtml = true;
            message.Subject = "IS Work Order - " + DateTime.Now.ToShortDateString();
            message.Body = @"<strong>Work Order description:</strong> " + model.Description + "<br />" +
                "<strong>Date submitted:</strong> " + DateTime.Now.ToShortDateString() + "<br />" +
                "<strong>Due Date:</strong> " + model.DueDate + "<br />" +
                "<strong>Category:</strong> " + model.category + "<br />" +
                "<strong>Machine Name:</strong> " + model.MachineName + "<br />" +
                "<strong>Urgency:</strong> " + model.Importance + "<br />" +
                "<strong>Status:</strong> " + model.Status + "<br />" +
                "<strong>Submitted by:</strong> " + model.Username;
            // Add a carbon copy recipient.
            //MailAddress copy = new MailAddress("jdwhaley@genext.com", "John Whaley");
            //message.CC.Add(copy);
            SmtpClient client = new SmtpClient(server);
            // Include credentials if the server requires them.
            //  client.Credentials = CredentialCache.DefaultNetworkCredentials;
            // Console.WriteLine("Sending an email message to {0} by using the SMTP host {1}.",
                //   to.Address, client.Host);

            try
            {
                client.Send(message);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public static void CreateResponse(string server, WorkOrderViewModel model)
        {            

            EmployeeConnection db = new EmployeeConnection();

            tblEmployee emp = db.tblEmployees.SingleOrDefault(x => x.UName == model.Username);
            string path = emp.EMail;

            MailAddress from = new MailAddress("abradley@genext.com", "Alan Bradley"); //change to alan bradley
            MailAddress to = new MailAddress(path, "Submitter");
            MailMessage message = new MailMessage(from, to);
            // message.Subject = "Using the SmtpClient class.";
            message.IsBodyHtml = true;
            message.Subject = "IS Work Order - " + DateTime.Now.ToShortDateString();
            message.Body = @"<strong>Work Order Status:</strong> " + model.Status + "<br />" +

ExpenseClient/Views/ISWorkOrder/Admin.cshtml
@model ExpenseClient.ViewModels.WorkOrderViewModel
@{
    ViewBag.Title = "Admin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Open Work Orders:</h2>

<!--jQuery Datatables with inline button and jQuery scripts to execute CRUD-->
<div style="width:100%; margin:0 auto;">
    <table id="Mytable" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
        <thead>
            <tr>
                
                @*<th>Date</th>*@
                <th>Submitter</th>             
                <th>Machine name</th>
                <th>Category</th>
                <th>Urgency</th>
                <th>Description</th>
                <th>Status</th>
                <th>Edit</th>
              
            </tr>
        </thead>
    </table>
</div>

<!--Modal11 pop-up which contains Partial1 form for Editing and submitting-->
<div class="modal fade in" id="myModal11">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <a href="#" class="close" data-dismiss="modal">&times;</a>
                <h3 class="modal-title">Edit WO</h3>
            </div>

            <div class="modal-body" id="myModalBodyDiv11">





            </div>


        </div>

    </div>

</div>

@section Scripts{

    <script>
        //GET data for jQuery Datatables
        $(document).ready(function () {

            GetRecords();
        })
        //GET data for jQuery Datatables
        var GetRecords = function () {

            $.ajax({

                type: "Get",
                url: "/ISWorkOrder/LoadData",
                success: function (response) {

                    BindTable(response);

                }
            })

        }
        //Fill Datatable with JSON response
        var BindTable = function (response) {

            $('#Mytable').DataTable({
                "data": response,
                "columns": [
                    
                    //{ "data": "Date", "autoWidth": true },
                    { "data": "Username", "autoWidth": true },                    
                    { "data": "Comp_Name", "autoWidth": true },
                    { "data": "category", "autoWidth": true },
                    { "data": "Importance", "autoWidth": true },
                    { "data": "Description", "autoWidth": true },
                    { "data": "Status", "autoWidth": true },                    
                    {
                        "data": "WorkOrderNumber",
                        "render": function (WorkOrderNumber, type, full, meta) {
                            return '<a class="btn btn-info" onclick="EditOrder(' + WorkOrderNumber + ')">Edit</a>';
                        }

                    },
                    
                ],

            });
        }
        //Execute edit, displays Modal1
        var EditOrder = function (workordernumber) {

            var url = "/ISWorkOrder/EditOrder?wo=" + workordernumber;

            $("#myModalBodyDiv11").load(url, function () {

                $("#myModal11").modal({ show: true });


            })

        }
    </script>

}

ExpenseClient/Views/ISWorkOrder/Index.cshtml
@model ExpenseClient.ViewModels.WorkOrderViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <div class="content">
        <img src="~/Site Content/geiBrandBoot.png" alt="GEI" />
        <h3 style="text-align: left; color: blue">IS Work Orders</h3>
    </div>

</div>

@using (Html.BeginForm("Index", "ISWorkOrder"))
{

<div class="container">
    <div class="row">
        <div class="col-sm-4">
            @Html.LabelFor(m => m.CategoryDropDown)
            @Html.DropDownListFor(m => m.category, new SelectList(Model.CategoryDropDown, "Category", "Category"), "Select Category", new { @class = "form-control" })
        </div>
        <div class="col-sm-4">
            @Html.LabelFor(m => m.UrgencyDropDown)
            @Html.DropDownListFor(m => m.Importance, new SelectList(Model.UrgencyDropDown, "Urgency", "Urgency"), "Select Urgency", new { @class = "form-control" })
        </div>
        <div class="col-sm-4">
            @Html.LabelFor(m => m.MachineName)
            @Html.TextBoxFor(m => m.MachineName, new { @class = "form-control" })
        </div>
    </div>
    <div class="row">
        <div class="col-sm-4">
            @Html.LabelFor(m => m.Date)
            @Html.TextBoxFor(m => m.Date, new { @class = "form-control" })
        </div>
        <div class="col-sm-4">
            @Html.LabelFor(m => m.Status)
            @Html.TextBoxFor(m => m.Status, new { @class = "form-control" })
        </div>

    </div>
    <br />
    <div class="row">

        <div class="col-sm-8">
            @Html.LabelFor(m => m.Description)
            @Html.TextAreaFor(m => m.Description, 10, 40, htmlAttributes: new { style = "width: 100%; max-width: 100%;", @class = "form-control", @Value = "Enter description of issue here..." })
        </div>
    </div>
    <br />    
    <div class="row">
        <div class="col-sm-4">
            <button type="submit" class="btn btn-primary btn-block" style="width: 280px;">Submit &raquo;</button>

        </div>
    </div>
</div>
              
 }

@section Scripts{

    <script>

    </script>

}