ExpenseClient/Models/Expense.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;

namespace ExpenseClient.Models
{
    public class Expense
    {
        public int EmployeeNum { get; set; }         
        public bool Reimburse { get; set; }
        public DateTime ExpenseDate { get; set; }
        public string CategoryID { get; set; }
        public int Attendees { get; set; }
        public int Mileage { get; set; }
        public string Place { get; set; }
        public string Purpose { get; set; }
        public string PersonsEntertained { get; set; }
        public int Amount { get; set; }
        
    }
}

ExpenseClient/ViewModels/EasterEggViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;


namespace ExpenseClient.ViewModels
{
    public class EasterEggViewModel
    {
        public string Name { get; set; }
        public int Count { get; set; }
    }
}

ExpenseClient/ViewModels/ExpenseViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ExpenseClient.Models;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;

namespace ExpenseClient.ViewModels
{
    public class ExpenseViewModel
    {
        
        [Display(Name = "Badge Number")]
        public string EmployeeNum { get; set; }

        
        [Display(Name = "User")]
        public string EmployeeName { get; set; }

        public DateTime WeekEndDate { get; set; }
        
        
        [Display(Name = "Date of Expense")]
        public DateTime? ExpenseDate { get; set; }

        public bool Reimburse { get; set; }
        
        
        [Display(Name = "Number of Attendees")]
        public int? Attendees { get; set; } 

        
        public decimal? Mileage { get; set; } 

        
        [Display(Name = "Place/City/State")]
        public string Place { get; set; }

        
        [Display(Name = "Business Purpose")]
        public string Purpose { get; set; }

       
        [Display(Name = "Persons Entertained")]
        public string PersonsEntertained { get; set; }

        
        public decimal? Amount { get; set; }

        
        [Display(Name = "Category")]
        public List<CatDropDown> CategoryDropDownProperty { get; set; } //property that refers the model that fills the drop down
        public string categoryid { get; set; } //property that holds drop down list values

        public DateTime Date { get; set; }

        public string AccountNum { get; set; }

        public bool CashAdvance { get; set; }

        
        [Display(Name = "Advanced Amount")]
        public float AdvanceAmt { get; set; }

        public bool Approved { get; set; }
        public int Line { get; set; }

        [Display(Name = "Select Date")]
        public DateTime? selDate { get; set; }
        
    }
    public class CatDropDown
    {
        public string CategoryID { get; set; }
        public string Categoryname { get; set; }
        public string Accountnum { get; set; }
    }
       
   
}

ExpenseClient/Controllers/ExpenseController.cs
using ExpenseClient.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ExpenseClient.ViewModels;
using System.Data.SqlClient;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core.Mapping;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Infrastructure.MappingViews;
using System.Threading.Tasks;
using AutoMapper.Mappers.Internal;
using AutoMapper.Features;
using AutoMapper.Execution;

namespace ExpenseClient.Controllers
{
    public class ExpenseController : Controller
    {
        private GEIConnection db = new GEIConnection();
        
        
        public List<CatDropDown> GetDetails() //populate dropdown and model bind
        {
            GEIConnection _context = new GEIConnection();
            List<CatDropDown> results = new List<CatDropDown>();
            var obj = _context.tblExpenseTables.Select(m => m).ToList();
            if (obj != null && obj.Count() > 0)
            {
                foreach (var data in obj)
                {
                    CatDropDown model = new CatDropDown();
                    model.Categoryname = data.CategoryName;
                    model.CategoryID = data.CategoryID;
                    model.Accountnum = data.AccountNum;
                    results.Add(model);
                }
            }

            return results;
        }
        
        // GET: Expense        
        public ActionResult Index()
        {
            EmployeeConnection db = new EmployeeConnection();

            string user = User.Identity.Name.Substring(9);
            
            ExpenseViewModel model = new ExpenseViewModel();
            model.CategoryDropDownProperty = GetDetails();            
            model.EmployeeName = user;
            model.EmployeeNum = db.tblEmployees
                .Where(s => s.UName == user)
                .Select(s => s.EmpBdgeNum).Single();
            
            return View(model);

        }
       
        [HttpPost]
        public ActionResult Index(ExpenseViewModel model) //overloaded index method
        {
            //validation
            if (model.categoryid == "2S" && model.Amount > 125)
            {
                return View("PhoneError");
            }
            if (model.categoryid == "3A" && model.Amount > model.Attendees * 10)
            {
                return View("MealError");
            }
            if (model.categoryid == "3B" && model.Amount > model.Attendees * 15)
            {
                return View("MealError");
            }
            if (model.categoryid == "3C" && model.Amount > model.Attendees * 25)
            {
                return View("MealError");
            }

            GEIConnection db = new GEIConnection();
            tblExpenseDetail dbo = new tblExpenseDetail();
            tblExpenseBasic dbheader = new tblExpenseBasic();

            string name = model.EmployeeName;
            string num = model.categoryid;

            var context = new EmployeeConnection();

            //week ending method
            DayOfWeek day = DateTime.Now.DayOfWeek;
            int days = day - DayOfWeek.Monday;
            DateTime start = DateTime.Now.AddDays(-days);
            DateTime weekEndDate = start.AddDays(6);

            //Header insert
            dbheader.EmployeeNum = context.tblEmployees
                .Where(m => m.UName == name)
                .Select(m => m.EmpBdgeNum).Single();
            dbheader.WeekEndingDate = weekEndDate;
            dbheader.Date = DateTime.Now;
            dbheader.CashAdvance = model.CashAdvance;
            dbheader.AdvanceAmount = model.AdvanceAmt;

            decimal rate = 0.555m;
            decimal? miles = model.Mileage;
            
            //Mileage calculation
            if (model.categoryid == "1")
            {
                model.Amount = miles * rate;

            }


            dbo.CategoryID = model.categoryid; //assigning the model properties to the table object                       
            dbo.ExpenseDate = model.ExpenseDate;            
            dbo.Mileage = model.Mileage;
            dbo.Amount = model.Amount;
            dbo.AccountNum = db.tblExpenseTables
                .Where(s => s.CategoryID == num)
                .Select(s => s.AccountNum).Single();
            dbo.Reimburse = model.Reimburse;
            dbo.NumOfAttendees = model.Attendees;
            dbo.BusinessPurpose = model.Purpose;
            dbo.PersonsEntertained = model.PersonsEntertained;
            dbo.PlaceCityState = model.Place;
            dbo.Name = model.EmployeeName;
            dbo.Date = DateTime.Now;
            dbo.WeekEndingDate = WeekEnd(model.ExpenseDate);
            dbo.EmployeeNum = context.tblEmployees
                .Where(m => m.UName == name)
                .Select(m => m.EmpBdgeNum).Single();


            if (ModelState.IsValid)
            {
                
                db.tblExpenseDetails.Add(dbo); //adding the table objects to record
                db.tblExpenseBasics.Add(dbheader);
                db.SaveChanges();

                return RedirectToAction("Index"); //redirect to non-overloaded index
            }
            else
            {
                return View(model);
            }
        }


        [HttpGet]
        public JsonResult LoadData()
        {
            //week ending method
            DayOfWeek day = DateTime.Now.DayOfWeek;
            int days = day - DayOfWeek.Monday;
            DateTime start = DateTime.Now.AddDays(-days);
            DateTime weekEndDate = start.AddDays(6);

            DateTime now = DateTime.Now;

            using (GEIConnection dc = new GEIConnection())
            {
                string user = User.Identity.Name.Substring(9);
                ExpenseViewModel model = new ExpenseViewModel();
                model.CategoryDropDownProperty = GetDetails();
                List<ExpenseViewModel> List = dc.tblExpenseDetails
                            .Where(o => o.Name == user && o.WeekEndingDate == weekEndDate.Date)
                            .ToList()
                            .Select(o => new ExpenseViewModel
                            {
                                categoryid = o.CategoryID,
                                ExpenseDate = o.ExpenseDate,
                                Amount = o.Amount,
                                Mileage = o.Mileage,
                                Line = o.Line,
                                EmployeeName = o.Name,
                                EmployeeNum = o.EmployeeNum,
                                Attendees = o.NumOfAttendees,
                                Place = o.PlaceCityState,
                                PersonsEntertained = o.PersonsEntertained,
                                Purpose = o.BusinessPurpose,
                                Reimburse = o.Reimburse
                            }).ToList();

                return Json(List, JsonRequestBehavior.AllowGet);
            }

        }


        public DateTime WeekEnd(DateTime? sel)
        {
            //week ending method            
             
            DayOfWeek day = sel.Value.Date.DayOfWeek;
            int days = day - DayOfWeek.Monday;
            DateTime start = sel.Value.AddDays(-days);
            DateTime weekEndDate = start.AddDays(6);

            return weekEndDate.Date;
        }

        [HttpPost]
        public ActionResult Edit(ExpenseViewModel model)
        {
            GEIConnection db = new GEIConnection();
            //week ending method
            DayOfWeek day = DateTime.Now.DayOfWeek;
            int days = day - DayOfWeek.Monday;
            DateTime start = DateTime.Now.AddDays(-days);
            DateTime weekEndDate = start.AddDays(6);
            
            string num = model.categoryid;

            try
            {              

                //Update
                var asset = db.tblExpenseDetails.SingleOrDefault(x => x.Line == model.Line);
                
                asset.CategoryID = model.categoryid;
                
                asset.ExpenseDate = model.ExpenseDate;
                asset.Amount = model.Amount;
                asset.Mileage = model.Mileage;
                asset.WeekEndingDate = WeekEnd(model.ExpenseDate);
                asset.BusinessPurpose = model.Purpose;
                asset.EmployeeNum = model.EmployeeNum;
                asset.Name = model.EmployeeName;
                asset.Date = DateTime.Now;
                asset.NumOfAttendees = model.Attendees;
                asset.PlaceCityState = model.Place;
                asset.PersonsEntertained = model.PersonsEntertained;
                asset.Reimburse = model.Reimburse;
                asset.AccountNum = db.tblExpenseTables
                .Where(s => s.CategoryID == num)
                .Select(s => s.AccountNum).Single();
                asset.Line = model.Line;
                db.SaveChanges();

                
                
                return RedirectToAction("Index");
            }
            catch (Exception x)
            {
                throw x;
            }
        }

        
        public ActionResult EditExpense(int? Line)
        {
            GEIConnection db = new GEIConnection();
            List<tblExpenseDetail> list = db.tblExpenseDetails.ToList();
            ViewBag.DepartmentList = list;

            ExpenseViewModel model = new ExpenseViewModel();
            model.CategoryDropDownProperty = GetDetails();
            if (Line > 0)
            {

                tblExpenseDetail emp = db.tblExpenseDetails.SingleOrDefault(x => x.Line == Line);
                model.ExpenseDate = emp.ExpenseDate;
                model.categoryid = emp.CategoryID;
                model.Amount = emp.Amount;
                model.Mileage = emp.Mileage;
                model.EmployeeName = emp.Name;

ExpenseClient/Views/Expense/Index.cshtml
@model ExpenseClient.ViewModels.ExpenseViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
<div class="page-header">
    <div class="content">
        <img src="~/Site Content/geiBrandBoot.png" alt="GEI" />
        <h3 style="text-align: left; color: blue">Expense Client</h3>
    </div>

</div>

@using (Html.BeginForm("Index", "Expense"))
{
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <div class="checkbox" style="padding-top:25px;">
                    <label>
                        @Html.CheckBoxFor(m => m.CashAdvance) Cash Advance
                    </label>

                </div>
            </div>
            <div class="col-sm-4">
                <div class="checkbox" style="padding-top:25px;">


                </div>
            </div>
            <div class="col-sm-4">
                <div class="checkbox" style="padding-top:25px;">
                    <label>
                        @Html.CheckBoxFor(m => m.Reimburse) Reimburse
                    </label>
                </div>

            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(m => m.EmployeeName)
                    @Html.TextBoxFor(m => m.EmployeeName, new { @class = "form-control " })
                    @Html.ValidationMessageFor(model => model.EmployeeName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(m => m.EmployeeNum)
                    @Html.TextBoxFor(m => m.EmployeeNum, new { @class = "form-control " })
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group" id="categoryid">
                    @Html.LabelFor(m => m.CategoryDropDownProperty)
                    @Html.DropDownListFor(m => m.categoryid, new SelectList(Model.CategoryDropDownProperty, "CategoryID", "Categoryname"), "Select ID", new { @id = "ID", @class = "form-control", onchange = "ShowDiv()" })


                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group" id="Amount">

                    @Html.LabelFor(m => m.Amount)
                    @Html.TextBoxFor(m => m.Amount, new { @class = "form-control", @Value = 0 })
                    @Html.ValidationMessageFor(m => m.Amount)
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(m => m.Attendees)
                    @Html.TextBoxFor(m => m.Attendees, new { @class = "form-control", @Value = 0 })
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(m => m.Place)
                    @Html.TextBoxFor(m => m.Place, new { @class = "form-control" })
                </div>

            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(m => m.PersonsEntertained)
                    @Html.TextBoxFor(m => m.PersonsEntertained, new { @class = "form-control" })
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(m => m.Purpose)
                    @Html.TextBoxFor(m => m.Purpose, new { @class = "form-control" })
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group" id="Mileage">
                    @Html.LabelFor(m => m.Mileage)
                    @Html.TextBoxFor(m => m.Mileage, new { @class = "form-control", @Value = 0 })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(m => m.ExpenseDate)
                    @Html.TextBoxFor(m => m.ExpenseDate, new { @class = "form-control", @Value = "01/01/2019" })
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(m => m.AdvanceAmt)
                    @Html.TextBoxFor(m => m.AdvanceAmt, new { @class = "form-control", @Value = 0 })
                </div>
            </div>
            <div class="col-sm-4" style="padding-top: 25px">
                <button type="submit" class="btn btn-primary btn-block" style="width: 280px;">Save &raquo;</button>
            </div>
        </div>
    </div>
}
<br />

<br />
<br />
<div class="container">



    <div style="text-align: center;">
        <h3 style="text-align: center; color: black;">Expenses for <strong style="color: blue;">@User.Identity.Name.Substring(9)</strong>:</h3>
        <h4 style="text-align: center; color: black;">Week:<strong style="color: blue;"> @DateTime.Now.Date.ToShortDateString()</strong></h4>

    </div>
    <a href="/ExpenseReporting/Report" class="btn btn-primary">Generate Report</a>
    <br />
    <br />
    <?PHP /* jQuery Datatables with inline button and jQuery scripts to execute CRUD */ ?>
    <div style="width:100%; margin:0 auto;">
        <table id="myTable" class="table table-striped table-row-border table-hover dt-responsive nowrap" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>Mileage</th>
                    <th>Amount</th>
                    <th>Attendees</th>
                    <th>Place</th>
                    <th>Persons</th>
                    <th>Purpose</th>
                    <th>Reimburse</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
        </table>
    </div>
    <button type="button" href="#" data-toggle="tooltip" class="btn btn-dark"
            title="If no expenses appear in the table above, then you have no registered expenses for the current week.
            To edit or view previous expenses, please use the above navigation bar to go to previous expenses">
        Help
    </button>
</div>

<?PHP /* Modal1 pop-up which contains Partial1 form for Editing and submitting */ ?>

<div class="modal fade in" id="myModal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <a href="#" class="close" data-dismiss="modal">&times;</a>
                <h3 class="modal-title">Edit Expense</h3>
            </div>
            <div class="modal-body" id="myModalBodyDiv1">





            </div>


        </div>

    </div>

</div>


@*outside of container*@

@section Scripts{

    <script>

                //GET data for jQuery Datatables 
                $(document).ready(function () {

                    GetEmployeeRecord();
                })
                //GET data for jQuery Datatables
                var GetEmployeeRecord = function () {

                    $.ajax({

                        type: "Get",
                        url: "/Expense/LoadData",
                        success: function (response) {

                            BindDataTable(response);

                        }
                    })

                }

            //Fill Datatable with JSON response
            var BindDataTable = function (response) {

                $('#myTable').DataTable({
                    "data": response,
                    //searching: false,
                    "columns": [
                        { "data": "Mileage", "autoWidth": true },
                        { "data": "Amount", "autoWidth": true },
                        { "data": "Attendees", "autoWidth": true },
                        { "data": "Place", "autoWidth": true },
                        { "data": "PersonsEntertained", "autoWidth": true },
                        { "data": "Purpose", "autoWidth": true },
                        { "data": "Reimburse", "autoWidth": true },
                        {
                            "data": "Line",
                            "render": function (Line, type, full, meta) {
                                //return '<a class="btn btn-info" onclick="EditExpense(' + Line + ')">Edit</a>';
                                return '<a class="btn" onclick="EditExpense(' + Line + ')"><span class="glyphicon glyphicon-pencil" /></a>';
                            }

                        },
                        {
                            "data": "Line",
                            "render": function (Line, type, full, meta) {
                                //return '<a class="btn btn-danger" onclick="DeleteRow(' + Line + ')">Delete</a>';
                                return '<a class="btn" onclick="DeleteRow(' + Line + ')"><span class="glyphicon glyphicon-remove" /></a>';
                            }
                        }
                    ]

                });
            }

            //Execute edit, displays Modal1
            var EditExpense = function (line) {

                var url = "/Expense/EditExpense?Line=" + line;

                $("#myModalBodyDiv1").load(url, function () {

                    $("#myModal1").modal({ show: true });


                })

            }



            //Executes Delete where model.Line == Line
            function DeleteRow(Line) {
                if (confirm("Are you sure you want to delete this record..?")) {
                    $.ajax({

                        type: 'POST',
                        url: "/Expense/delete?Line=" + Line,
                        datatype: 'JSON',
                        success: function (response) {
                            if (response == "success") {

                                alert("Data deleted successfully..");
                                window.location.reload();
                                //$("#myModal").modal('hide');
                            }
                        },
                        error: function (msg) {
                            alert(msg.responseText);
                        }

                    });
                }
            }


            //f(x) to remove fade class on IE browsers
            $(function () {
                var isIE = window.ActiveXObject || "ActiveXObject" in window;
                if (isIE) {
                    $('.modal').removeClass('fade');
                }
            });

            //f(x) to hide DOM objects based on user selection
            function ShowDiv() {
                $("#categoryid").on("change", function () {
                    if ($("#categoryid option:selected").val() == 1) {
                        $("#Amount").hide();
                        $("#Mileage").show();
                    }
                    else {
                        $("#Amount").show();
                        $("#Mileage").hide();
                    }

                })
            };



    </script>

}

ExpenseClient/Views/Expense/Previous.cshtml
@model ExpenseClient.ViewModels.ExpenseViewModel
@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
<div class="content">

    <img src="~/Site Content/geiBrandBoot.png" />
    <h3 style="padding-right: 40px; color: blue;">Edit Previous Expenses</h3>

    @*<a href="#" id="btn" class="btn btn-warning btn-sm">Fill Table</a>*@
</div>



<br />
<br />

<!--Modal2 pop-up which contains Partial3 form data for datepicker-->
<div class="modal fade in" id="myModal2">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <a href="#" class="close" data-dismiss="modal">&times;</a>
                <h3 class="modal-title">Date</h3>
            </div>

            <div class="modal-body" id="myModalBodyDiv2">
                                             

            </div>


        </div>

    </div>

</div>

<!--Modal1 to inline edit expenses after datatables are filled-->
<div class="modal fade in" id="myModal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <a href="#" class="close" data-dismiss="modal">&times;</a>
                <h3 class="modal-title">Edit Expense</h3>
            </div>
            <div class="modal-body" id="myModalBodyDiv1">





            </div>


        </div>

    </div>

</div>
<div class="container">

    <a href="/ExpenseReporting/PreviousReports" class="btn btn-primary">Generate Report</a>
    <a href="#" id="btn" class="btn btn-warning">Fill Table</a>
    <br />
    <br />
    <!--jQuery Datatable-->
    <div style="width:100%; margin:0 auto;">
        <table id="myTabl" class="table table-striped table-hover table-row-border dt-responsive nowrap" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>Mileage</th>
                    <th>Amount</th>
                    <th>Attendees</th>
                    <th>Place</th>
                    <th>Persons</th>
                    <th>Purpose</th>
                    <th>Reimburse</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
        </table>
    </div>
</div>
@section Scripts{

    <script>

        $(function () {


            $("#btn").click(function () {


                //Load Modal2 to prompt user for date value

                var url = "/Expense/ModalPopUpp/";

                $("#myModalBodyDiv2").load(url, function () {

                    $("#myModal2").modal({ show: true });


                })

            });
        });
        //Fill Previous.cshtml datatable with JSON response from user input
        var BindMe = function (response) {

            $('#myTabl').DataTable({
                "datatype": "json",
                "data": response,
                "columns": [
                    { "data": "Mileage", "autoWidth": true },
                    { "data": "Amount", "autoWidth": true },
                    { "data": "Attendees", "autoWidth": true },
                    { "data": "Place", "autoWidth": true },
                    { "data": "PersonsEntertained", "autoWidth": true },
                    { "data": "Purpose", "autoWidth": true },
                    { "data": "Reimburse", "autoWidth": true },
                    {
                        "data": "Line",
                        "render": function (Line, type, full, meta) {
                            //return '<a class="btn btn-info" onclick="EditExpense(' + Line + ')">Edit</a>';
                            return '<a class="btn" onclick="EditExpense(' + Line + ')"><span class="glyphicon glyphicon-pencil" /></a>';
                        }

                    },
                    {
                        "data": "Line",
                        "render": function (Line, type, full, meta) {
                            //return '<a class="btn btn-danger" onclick="DeleteRow(' + Line + ')">Delete</a>';
                            return '<a class="btn" onclick="DeleteRow(' + Line + ')"><span class="glyphicon glyphicon-remove" /></a>';
                        }
                    }
                ]


            });
        }
        //Inline edit filled datatable => load Modal1
        var EditExpense = function (line) {

            var url = "/Expense/EditExpense?Line=" + line;

            $("#myModalBodyDiv1").load(url, function () {

                $("#myModal1").modal({ show: true });


            })

        }



        //Inline delete filled datatable where => m.line == Line
        function DeleteRow(Line) {
            if (confirm("Are you sure you want to delete this record..?")) {
                $.ajax({

                    type: 'POST',
                    url: "/Expense/delete?Line=" + Line,
                    datatype: 'JSON',
                    success: function (response) {
                        if (response == "success") {

                            alert("Data deleted successfully..");
                            window.location.reload();

                        }
                    },
                    error: function (msg) {
                        alert(msg.responseText);
                    }

                });
            }
        }
    </script>
}